# Defines Managers
services: 
    # Warehouse Manager
    aiomedia_warehouse.manager.warehouse: 
        class:     %aiomedia_warehouse.manager.warehouse.class%
        arguments:
            entityManager:   @doctrine.orm.entity_manager